# Generated by Django 4.1.6 on 2023-02-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_remove_patient_assigneddoctorid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgid', models.IntegerField(blank=True)),
                ('images', models.FileField(blank=True, upload_to='blog/')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('Summary', models.CharField(blank=True, max_length=500)),
                ('content', models.CharField(blank=True, max_length=99999)),
                ('is_draft', models.BooleanField(default='No')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms.doctor')),
            ],
        ),
    ]
