# Generated by Django 4.1.6 on 2023-02-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_alter_blog_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fullname',
            field=models.CharField(default='Vishal Kharche', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='imagepath',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
